// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _11_MVC_FulboolOrnek.Context;

#nullable disable

namespace _11_MVC_FulboolOrnek.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805175355_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_11_MVC_FulboolOrnek.Models.Futbolcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MevkiID")
                        .HasColumnType("int");

                    b.Property<int>("TakimID")
                        .HasColumnType("int");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MevkiID");

                    b.HasIndex("TakimID");

                    b.ToTable("Futbolcu");
                });

            modelBuilder.Entity("_11_MVC_FulboolOrnek.Models.Mevki", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mevki");
                });

            modelBuilder.Entity("_11_MVC_FulboolOrnek.Models.Takim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeknikDirektörAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Takim");
                });

            modelBuilder.Entity("_11_MVC_FulboolOrnek.Models.Futbolcu", b =>
                {
                    b.HasOne("_11_MVC_FulboolOrnek.Models.Mevki", "Mevki")
                        .WithMany()
                        .HasForeignKey("MevkiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_11_MVC_FulboolOrnek.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mevki");

                    b.Navigation("Takim");
                });
#pragma warning restore 612, 618
        }
    }
}
