// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _19_MVC_RepositorySchool.Models.Context;

#nullable disable

namespace _19_MVC_RepositorySchool.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_19_MVC_RepositorySchool.Models.Ogrenci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenciAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OgrenciDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciOkulu")
                        .HasColumnType("int");

                    b.Property<byte>("OgrenciSinifi")
                        .HasColumnType("tinyint");

                    b.Property<string>("OgrenciSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciVeliTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OgrenciOkulu");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("_19_MVC_RepositorySchool.Models.Okul", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulEposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OkulID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OkulKuruluşTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OkulTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Okullar");
                });

            modelBuilder.Entity("_19_MVC_RepositorySchool.Models.Ogrenci", b =>
                {
                    b.HasOne("_19_MVC_RepositorySchool.Models.Okul", "OgrencininOkulu")
                        .WithMany("OkulOgrencileri")
                        .HasForeignKey("OgrenciOkulu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgrencininOkulu");
                });

            modelBuilder.Entity("_19_MVC_RepositorySchool.Models.Okul", b =>
                {
                    b.Navigation("OkulOgrencileri");
                });
#pragma warning restore 612, 618
        }
    }
}
